{% set version = "5.6.3" %}

package:
  name: pyutilib
  version: {{ version }}

source:
  fn: PyUtilib-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/P/PyUtilib/PyUtilib-{{ version }}.tar.gz
  md5: 4a050965097ae12384a1ebe85daf1983

build:
  number: 1000
  #noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

  entry_points:
    - test.pyutilib=pyutilib.dev.runtests:runPyUtilibTests
    - lbin=pyutilib.dev.lbin:main
    - lpython=pyutilib.dev.lpython:main
    - pypi_downloads=pyutilib.dev.pypi_downloads:main
    - replacecopyright=pyutilib.dev.replaceCopyright:main
    - checkcopyright=pyutilib.dev.checkCopyright:main
    - pyutilib_test_driver=pyutilib.autotest.driver:main
    - dispatch_srvr=pyutilib.pyro.dispatch_srvr:main

requirements:
  host:
    - python
    - pip

  run:
    - python
    #- setuptools
    - nose
    - six

test:
  imports:
    - pyutilib
    - pyutilib.autotest
    - pyutilib.autotest.tests
    - pyutilib.common
    - pyutilib.component
    - pyutilib.component.app
    - pyutilib.component.app.tests
    - pyutilib.component.config
    - pyutilib.component.config.tests
    - pyutilib.component.core
    - pyutilib.component.core.tests
    - pyutilib.component.executables
    - pyutilib.component.loader
    - pyutilib.component.loader.tests
    - pyutilib.dev
    - pyutilib.dev.tests
    - pyutilib.enum
    - pyutilib.enum.tests
    - pyutilib.excel
    - pyutilib.excel.tests
    - pyutilib.math
    - pyutilib.math.tests
    - pyutilib.misc
    - pyutilib.misc.tests
    - pyutilib.misc.tests.import_data
    - pyutilib.misc.tests.import_data.a
    - pyutilib.misc.tests.import_data.b
    - pyutilib.ply
    - pyutilib.pyro
    - pyutilib.services
    - pyutilib.subprocess
    - pyutilib.subprocess.tests
    - pyutilib.th
    - pyutilib.th.tests
    - pyutilib.workflow
    - pyutilib.workflow.tests

  commands:
    - test.pyutilib --help
    - pyutilib_test_driver --help
    - command -v lbin       # [unix]
    - where lbin            # [win]
    - command -v lpython    # [unix]
    - where lpython         # [win]
    - dispatch_srvr --help

about:
  home: https://github.com/PyUtilib/pyutilib
  license: BSD Clause
  license_family: BSD
  summary: 'PyUtilib: A collection of Python utilities'

extra:
  recipe-maintainers:
    - whart222
    - jsiirola
    - juanlu001
