appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: XUIuUpX7/xDEdmBgvuUyxTBYhzH46bl70YdSlzUI6dyi3dRn8Ch54wsNRim7kcvdS6tF2fito+9bAhj00DlHOAhBvNisx2JxDciH/2fPyW/kyAY1DP97/E1ZamGjWsyfEe4MVnJbYF+5tqMaZJN4juHfXsLXksv9OpPo+8hLxe88f8LnU0uDhkIfUQC/yeixsouzs2G8O+ELlDcelb2cSsRpSqDKSVlwps7UcTaV/wkKmB4GGZ7oXDH2/JACrcFOyKu5n8HOPL/E1QqYAgz/iarBaUGICS+/zCzqY0xnkrOqo2dab8I+xCNC8jw9WbLhYeYEIuDwxJrWaWjkS9701tuHXwwNnZyKsdMslDomdOpOzZzVoBIT3l9YgmDFX/u8YmkeAKsWwPqiWi7e+Mo7GNF5pqUN2kPSy+WsDmy3E6BqjUB+rkTa6NfeKj9QjhSYZfNpFc9kWuw1N7vZMWVk5zmgq0bzuNfM3uSvgaa8UhHgtLCIXTxqcfISyDuJxj/WU8D2QYD19b2Rp2rHJ74z0Dz6MNUtZRTGybU0hTpq5ebVrs5lOWFzaJnOQcLvMHF3zVzpSmBkDmsY+GZZ1F6jkfS+4i6QXTFB9lEhT25mBfSmrHxeXZljD+Z5iKki0pheqKGLn4LivoQ91igmCtQpBkO0sUYe8ix0hgPzSQQhKzQ=}
